#version 430 core

layout(local_size_x = 256) in;

layout(std430, binding = 1) buffer PositionPredict {
    vec4 positionPredict[];
};

layout(std430, binding = 13) buffer DeltaPosition {
    vec4 deltaPosition[];
};

uniform uint PARTICLE_COUNT;

void main() {
    uint index = gl_GlobalInvocationID.x;
    if (index >= PARTICLE_COUNT) {
        return;
    }
    positionPredict[index] += deltaPosition[index];
}
