#version 430 core

layout(local_size_x = 1) in;

layout(std430, binding = 3) buffer ParticleCountPerCube {
    uint particleCountPerCube[];
};

layout(std430, binding = 4) buffer CubeOffset {
    uint cubeOffset[];
};

layout(std430, binding = 6) buffer BlockOffset {
    uint blockOffset[];
};

uniform uint CUBE_COUNT_SQRT;

// only one invocation
void main() {
    for (uint i = 1; i < CUBE_COUNT_SQRT; i++) {
        blockOffset[i] += blockOffset[i - 1];
    }
}
