#version 430 core

layout(local_size_x = 1) in;

layout(std430, binding = 3) buffer ParticleCountPerCube {
    uint particleCountPerCube[];
};

layout(std430, binding = 4) buffer CubeOffset {
    uint cubeOffset[];
};

uniform uint CUBE_COUNT;

void main() {
    cubeOffset[0] = 0;
    for (int i = 1; i < CUBE_COUNT; i++) {
        cubeOffset[i] = cubeOffset[i - 1] + particleCountPerCube[i - 1];
    }
}